# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller-plugin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesan-csi-controller-plugin
  namespace: system
  labels:
    app.kubernetes.io/name: kubesan-csi-controller-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubesan-csi-controller-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubesan-csi-controller-plugin
        app.kubernetes.io/part-of: ksan-storage
        app.kubernetes.io/component: csi-controller-plugin
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      serviceAccountName: csi-controller-plugin
      containers:
        - name: csi-plugin
          image: kubesan
          args:
            - csi-controller-plugin
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
            - name: dev
              mountPath: /dev
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
          args:
            - --extra-create-metadata  # to get PVC/PV info in CreateVolume()
            - --default-fstype=ext4 # default FSType so that SecurityContext fsGroup works
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3
          args:
            - --extra-create-metadata  # to get VS/VSC info in CreateSnapshot()
          volumeMounts:
            - name: socket-dir
              mountPath: /run/csi
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/kubesan-controller
            type: DirectoryOrCreate
        - name: dev
          hostPath:
            path: /dev
            type: Directory
