# permissions for end users to view ksannodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ksan
    app.kubernetes.io/managed-by: kustomize
  name: ksannode-viewer-role
rules:
- apiGroups:
  - ksan.openshift.io
  resources:
  - ksannodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ksan.openshift.io
  resources:
  - ksannodes/status
  verbs:
  - get
