---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ksan.openshift.io
  resources:
  - ksanstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ksan.openshift.io
  resources:
  - ksanstorages/finalizers
  verbs:
  - update
- apiGroups:
  - ksan.openshift.io
  resources:
  - ksanstorages/status
  verbs:
  - get
  - patch
  - update
