---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ksan-operator.storage.openshift.io.ksan-operator.storage.openshift.io
  resources:
  - kubesans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ksan-operator.storage.openshift.io.ksan-operator.storage.openshift.io
  resources:
  - kubesans/finalizers
  verbs:
  - update
- apiGroups:
  - ksan-operator.storage.openshift.io.ksan-operator.storage.openshift.io
  resources:
  - kubesans/status
  verbs:
  - get
  - patch
  - update
