# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesan-cluster-controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: kubesan-cluster-controller-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubesan-cluster-controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubesan-cluster-controller-manager
        app.kubernetes.io/part-of: ksan-storage
        app.kubernetes.io/component: cluster-controller-manager
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      serviceAccountName: cluster-controller-manager-kubesan
      terminationGracePeriodSeconds: 10
      hostPID: true
      containers:
        - name: manager
          image: kubesan
          args:
            - cluster-controller-manager
            - --leader-elect
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            privileged: true
